# Signing Release Keys
release_key.store=/Users/AbdelrahmanOmer/Documents/e-commerce-release-keystore.jks
release_store.password=123456
release_key.alias=release
release_key.password=123456

# Signing Qa Keys
qa_key.store=/Users/AbdelrahmanOmer/Documents/e-commerce-qa-keystore.jks
qa_store.password=123456
qa_key.alias=qa
qa_key.password=123456

# API End Points
dev.prod_endpoint="https\://prod.myapp.com/"
dev.qa_endpoint="https\://qa.myapp.com/"
dev.debug_endpoint="https\://test.myapp.com/"

# Others
dev.project.certificate_pin="sha256/EULwX@sgihagsdihWAskshdUpShUo9mUTAskFARTg="
dev.db_version=1
dev.clear_cache=false
dev.map_key="dskffhoipdkf"
release.map_key="dskffhoipdkf"